# -*- coding: utf-8 -*-
"""
Author: @heyao

Created On: 2019/7/4 上午10:34
"""
NORMAL = 0
DISEASE = 1
SYMPTOM = 2
BODY = 3
DEGREE = 4
NEGATIVE = 5
CONJUNCTION = 6
LOCATION = 7
PUNCTUATION = 8
DATE_RANGE = 9
CHECK = 10
DATE_TIME = 11
YIN_YANG = 12
AREA = 13
SURGERY = 14
UNIT = 15
CHECK_TARGET = 16
COLOR = 17
DEGREE_WORD = 18
SPECIAL_WORD = 19

word_category_mapping = {
    NORMAL: "NORMAL",
    DISEASE: "DISEASE",
    SYMPTOM: "SYMPTOM",
    BODY: "BODY",
    DEGREE: "DEGREE",
    NEGATIVE: "NEGATIVE",
    CONJUNCTION: "CONJUNCTION",
    LOCATION: "LOCATION",
    PUNCTUATION: "PUNCTUATION",
    DATE_RANGE: "DATE_RANGE",
    CHECK: "CHECK",
    DATE_TIME: "DATE_TIME",
    YIN_YANG: "YIN_YANG",
    AREA: "AREA",
    SURGERY: "SURGERY",
    UNIT: "UNIT",
    CHECK_TARGET: "CHECK_TARGET",
    COLOR: "COLOR",
    DEGREE_WORD: "DEGREE_WORD",
    SPECIAL_WORD: "SPECIAL_WORD"
}
